[package]
name = "rustyjs-template"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.7.0"
napi-derive = "2.7.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
